// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: sync/sync.proto

package sync

import (
	common "github.com/DarkXPixel/Vibe/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetStateRequest) Reset() {
	*x = GetStateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_sync_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateRequest) ProtoMessage() {}

func (x *GetStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_sync_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateRequest.ProtoReflect.Descriptor instead.
func (*GetStateRequest) Descriptor() ([]byte, []int) {
	return file_sync_sync_proto_rawDescGZIP(), []int{0}
}

func (x *GetStateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetStateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pts          int64 `protobuf:"varint,1,opt,name=pts,proto3" json:"pts,omitempty"`
	UnorderedPts int64 `protobuf:"varint,2,opt,name=unordered_pts,json=unorderedPts,proto3" json:"unordered_pts,omitempty"`
}

func (x *GetStateResponse) Reset() {
	*x = GetStateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_sync_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateResponse) ProtoMessage() {}

func (x *GetStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_sync_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateResponse.ProtoReflect.Descriptor instead.
func (*GetStateResponse) Descriptor() ([]byte, []int) {
	return file_sync_sync_proto_rawDescGZIP(), []int{1}
}

func (x *GetStateResponse) GetPts() int64 {
	if x != nil {
		return x.Pts
	}
	return 0
}

func (x *GetStateResponse) GetUnorderedPts() int64 {
	if x != nil {
		return x.UnorderedPts
	}
	return 0
}

type GetDifferenceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId       string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Pts          int64  `protobuf:"varint,2,opt,name=pts,proto3" json:"pts,omitempty"`
	UnorderedPts int64  `protobuf:"varint,3,opt,name=unordered_pts,json=unorderedPts,proto3" json:"unordered_pts,omitempty"`
}

func (x *GetDifferenceRequest) Reset() {
	*x = GetDifferenceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_sync_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDifferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDifferenceRequest) ProtoMessage() {}

func (x *GetDifferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_sync_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDifferenceRequest.ProtoReflect.Descriptor instead.
func (*GetDifferenceRequest) Descriptor() ([]byte, []int) {
	return file_sync_sync_proto_rawDescGZIP(), []int{2}
}

func (x *GetDifferenceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetDifferenceRequest) GetPts() int64 {
	if x != nil {
		return x.Pts
	}
	return 0
}

func (x *GetDifferenceRequest) GetUnorderedPts() int64 {
	if x != nil {
		return x.UnorderedPts
	}
	return 0
}

type GetDifferenceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewPts          int64            `protobuf:"varint,1,opt,name=new_pts,json=newPts,proto3" json:"new_pts,omitempty"`
	NewUnorderedPts int64            `protobuf:"varint,2,opt,name=new_unordered_pts,json=newUnorderedPts,proto3" json:"new_unordered_pts,omitempty"`
	Updates         []*common.Update `protobuf:"bytes,3,rep,name=updates,proto3" json:"updates,omitempty"`
}

func (x *GetDifferenceResponse) Reset() {
	*x = GetDifferenceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_sync_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDifferenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDifferenceResponse) ProtoMessage() {}

func (x *GetDifferenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_sync_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDifferenceResponse.ProtoReflect.Descriptor instead.
func (*GetDifferenceResponse) Descriptor() ([]byte, []int) {
	return file_sync_sync_proto_rawDescGZIP(), []int{3}
}

func (x *GetDifferenceResponse) GetNewPts() int64 {
	if x != nil {
		return x.NewPts
	}
	return 0
}

func (x *GetDifferenceResponse) GetNewUnorderedPts() int64 {
	if x != nil {
		return x.NewUnorderedPts
	}
	return 0
}

func (x *GetDifferenceResponse) GetUpdates() []*common.Update {
	if x != nil {
		return x.Updates
	}
	return nil
}

type GetSnapshotRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId       string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LimitPerChat int32  `protobuf:"varint,2,opt,name=limit_per_chat,json=limitPerChat,proto3" json:"limit_per_chat,omitempty"`
}

func (x *GetSnapshotRequest) Reset() {
	*x = GetSnapshotRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_sync_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapshotRequest) ProtoMessage() {}

func (x *GetSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_sync_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_sync_sync_proto_rawDescGZIP(), []int{4}
}

func (x *GetSnapshotRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetSnapshotRequest) GetLimitPerChat() int32 {
	if x != nil {
		return x.LimitPerChat
	}
	return 0
}

type GetSnapshotResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewPts          int64                `protobuf:"varint,1,opt,name=new_pts,json=newPts,proto3" json:"new_pts,omitempty"`
	NewUnorderedPts int64                `protobuf:"varint,2,opt,name=new_unordered_pts,json=newUnorderedPts,proto3" json:"new_unordered_pts,omitempty"`
	Chats           []*common.ChatState  `protobuf:"bytes,3,rep,name=chats,proto3" json:"chats,omitempty"`
	Profile         *common.ProfileState `protobuf:"bytes,4,opt,name=profile,proto3" json:"profile,omitempty"`
}

func (x *GetSnapshotResponse) Reset() {
	*x = GetSnapshotResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_sync_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapshotResponse) ProtoMessage() {}

func (x *GetSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_sync_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapshotResponse.ProtoReflect.Descriptor instead.
func (*GetSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_sync_sync_proto_rawDescGZIP(), []int{5}
}

func (x *GetSnapshotResponse) GetNewPts() int64 {
	if x != nil {
		return x.NewPts
	}
	return 0
}

func (x *GetSnapshotResponse) GetNewUnorderedPts() int64 {
	if x != nil {
		return x.NewUnorderedPts
	}
	return 0
}

func (x *GetSnapshotResponse) GetChats() []*common.ChatState {
	if x != nil {
		return x.Chats
	}
	return nil
}

func (x *GetSnapshotResponse) GetProfile() *common.ProfileState {
	if x != nil {
		return x.Profile
	}
	return nil
}

var File_sync_sync_proto protoreflect.FileDescriptor

var file_sync_sync_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x73, 0x79, 0x6e, 0x63, 0x2f, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x73, 0x79, 0x6e, 0x63, 0x1a, 0x12, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2a, 0x0a, 0x0f, 0x47,
	0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x49, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x70,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x70, 0x74, 0x73, 0x12, 0x23, 0x0a,
	0x0d, 0x75, 0x6e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x65, 0x64, 0x5f, 0x70, 0x74, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x75, 0x6e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x65, 0x64, 0x50,
	0x74, 0x73, 0x22, 0x66, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x44, 0x69, 0x66, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x03, 0x70, 0x74, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x75, 0x6e, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x65, 0x64, 0x5f, 0x70, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x75, 0x6e,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x65, 0x64, 0x50, 0x74, 0x73, 0x22, 0x86, 0x01, 0x0a, 0x15, 0x47,
	0x65, 0x74, 0x44, 0x69, 0x66, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x65, 0x77, 0x5f, 0x70, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6e, 0x65, 0x77, 0x50, 0x74, 0x73, 0x12, 0x2a, 0x0a,
	0x11, 0x6e, 0x65, 0x77, 0x5f, 0x75, 0x6e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x65, 0x64, 0x5f, 0x70,
	0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x6e, 0x65, 0x77, 0x55, 0x6e, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x65, 0x64, 0x50, 0x74, 0x73, 0x12, 0x28, 0x0a, 0x07, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x07, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x73, 0x22, 0x53, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68,
	0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x5f, 0x70, 0x65, 0x72, 0x5f,
	0x63, 0x68, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x50, 0x65, 0x72, 0x43, 0x68, 0x61, 0x74, 0x22, 0xb3, 0x01, 0x0a, 0x13, 0x47, 0x65, 0x74,
	0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x17, 0x0a, 0x07, 0x6e, 0x65, 0x77, 0x5f, 0x70, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x6e, 0x65, 0x77, 0x50, 0x74, 0x73, 0x12, 0x2a, 0x0a, 0x11, 0x6e, 0x65, 0x77,
	0x5f, 0x75, 0x6e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x65, 0x64, 0x5f, 0x70, 0x74, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x6e, 0x65, 0x77, 0x55, 0x6e, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x65, 0x64, 0x50, 0x74, 0x73, 0x12, 0x27, 0x0a, 0x05, 0x63, 0x68, 0x61, 0x74, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x68,
	0x61, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x63, 0x68, 0x61, 0x74, 0x73, 0x12, 0x2e,
	0x0a, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x32, 0x48,
	0x0a, 0x0b, 0x53, 0x79, 0x6e, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x39, 0x0a,
	0x08, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x15, 0x2e, 0x73, 0x79, 0x6e, 0x63,
	0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x16, 0x2e, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x44, 0x61, 0x72, 0x6b, 0x58, 0x50, 0x69, 0x78, 0x65,
	0x6c, 0x2f, 0x56, 0x69, 0x62, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x79, 0x6e,
	0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sync_sync_proto_rawDescOnce sync.Once
	file_sync_sync_proto_rawDescData = file_sync_sync_proto_rawDesc
)

func file_sync_sync_proto_rawDescGZIP() []byte {
	file_sync_sync_proto_rawDescOnce.Do(func() {
		file_sync_sync_proto_rawDescData = protoimpl.X.CompressGZIP(file_sync_sync_proto_rawDescData)
	})
	return file_sync_sync_proto_rawDescData
}

var file_sync_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_sync_sync_proto_goTypes = []interface{}{
	(*GetStateRequest)(nil),       // 0: sync.GetStateRequest
	(*GetStateResponse)(nil),      // 1: sync.GetStateResponse
	(*GetDifferenceRequest)(nil),  // 2: sync.GetDifferenceRequest
	(*GetDifferenceResponse)(nil), // 3: sync.GetDifferenceResponse
	(*GetSnapshotRequest)(nil),    // 4: sync.GetSnapshotRequest
	(*GetSnapshotResponse)(nil),   // 5: sync.GetSnapshotResponse
	(*common.Update)(nil),         // 6: common.Update
	(*common.ChatState)(nil),      // 7: common.ChatState
	(*common.ProfileState)(nil),   // 8: common.ProfileState
}
var file_sync_sync_proto_depIdxs = []int32{
	6, // 0: sync.GetDifferenceResponse.updates:type_name -> common.Update
	7, // 1: sync.GetSnapshotResponse.chats:type_name -> common.ChatState
	8, // 2: sync.GetSnapshotResponse.profile:type_name -> common.ProfileState
	0, // 3: sync.SyncService.GetState:input_type -> sync.GetStateRequest
	1, // 4: sync.SyncService.GetState:output_type -> sync.GetStateResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_sync_sync_proto_init() }
func file_sync_sync_proto_init() {
	if File_sync_sync_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sync_sync_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sync_sync_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sync_sync_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDifferenceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sync_sync_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDifferenceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sync_sync_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSnapshotRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sync_sync_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSnapshotResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sync_sync_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sync_sync_proto_goTypes,
		DependencyIndexes: file_sync_sync_proto_depIdxs,
		MessageInfos:      file_sync_sync_proto_msgTypes,
	}.Build()
	File_sync_sync_proto = out.File
	file_sync_sync_proto_rawDesc = nil
	file_sync_sync_proto_goTypes = nil
	file_sync_sync_proto_depIdxs = nil
}
