// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: sync/sync.proto

package sync

import (
	common "github.com/DarkXPixel/Vibe/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateRequest) Reset() {
	*x = GetStateRequest{}
	mi := &file_sync_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateRequest) ProtoMessage() {}

func (x *GetStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateRequest.ProtoReflect.Descriptor instead.
func (*GetStateRequest) Descriptor() ([]byte, []int) {
	return file_sync_sync_proto_rawDescGZIP(), []int{0}
}

func (x *GetStateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pts           int64                  `protobuf:"varint,1,opt,name=pts,proto3" json:"pts,omitempty"`
	UnorderedPts  int64                  `protobuf:"varint,2,opt,name=unordered_pts,json=unorderedPts,proto3" json:"unordered_pts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateResponse) Reset() {
	*x = GetStateResponse{}
	mi := &file_sync_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateResponse) ProtoMessage() {}

func (x *GetStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateResponse.ProtoReflect.Descriptor instead.
func (*GetStateResponse) Descriptor() ([]byte, []int) {
	return file_sync_sync_proto_rawDescGZIP(), []int{1}
}

func (x *GetStateResponse) GetPts() int64 {
	if x != nil {
		return x.Pts
	}
	return 0
}

func (x *GetStateResponse) GetUnorderedPts() int64 {
	if x != nil {
		return x.UnorderedPts
	}
	return 0
}

type GetDifferenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Pts           int64                  `protobuf:"varint,2,opt,name=pts,proto3" json:"pts,omitempty"`
	UnorderedPts  int64                  `protobuf:"varint,3,opt,name=unordered_pts,json=unorderedPts,proto3" json:"unordered_pts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDifferenceRequest) Reset() {
	*x = GetDifferenceRequest{}
	mi := &file_sync_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDifferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDifferenceRequest) ProtoMessage() {}

func (x *GetDifferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDifferenceRequest.ProtoReflect.Descriptor instead.
func (*GetDifferenceRequest) Descriptor() ([]byte, []int) {
	return file_sync_sync_proto_rawDescGZIP(), []int{2}
}

func (x *GetDifferenceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetDifferenceRequest) GetPts() int64 {
	if x != nil {
		return x.Pts
	}
	return 0
}

func (x *GetDifferenceRequest) GetUnorderedPts() int64 {
	if x != nil {
		return x.UnorderedPts
	}
	return 0
}

type GetDifferenceResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NewPts          int64                  `protobuf:"varint,1,opt,name=new_pts,json=newPts,proto3" json:"new_pts,omitempty"`
	NewUnorderedPts int64                  `protobuf:"varint,2,opt,name=new_unordered_pts,json=newUnorderedPts,proto3" json:"new_unordered_pts,omitempty"`
	Updates         []*common.Update       `protobuf:"bytes,3,rep,name=updates,proto3" json:"updates,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetDifferenceResponse) Reset() {
	*x = GetDifferenceResponse{}
	mi := &file_sync_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDifferenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDifferenceResponse) ProtoMessage() {}

func (x *GetDifferenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDifferenceResponse.ProtoReflect.Descriptor instead.
func (*GetDifferenceResponse) Descriptor() ([]byte, []int) {
	return file_sync_sync_proto_rawDescGZIP(), []int{3}
}

func (x *GetDifferenceResponse) GetNewPts() int64 {
	if x != nil {
		return x.NewPts
	}
	return 0
}

func (x *GetDifferenceResponse) GetNewUnorderedPts() int64 {
	if x != nil {
		return x.NewUnorderedPts
	}
	return 0
}

func (x *GetDifferenceResponse) GetUpdates() []*common.Update {
	if x != nil {
		return x.Updates
	}
	return nil
}

type GetSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LimitPerChat  int32                  `protobuf:"varint,2,opt,name=limit_per_chat,json=limitPerChat,proto3" json:"limit_per_chat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSnapshotRequest) Reset() {
	*x = GetSnapshotRequest{}
	mi := &file_sync_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapshotRequest) ProtoMessage() {}

func (x *GetSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_sync_sync_proto_rawDescGZIP(), []int{4}
}

func (x *GetSnapshotRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetSnapshotRequest) GetLimitPerChat() int32 {
	if x != nil {
		return x.LimitPerChat
	}
	return 0
}

type GetSnapshotResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NewPts          int64                  `protobuf:"varint,1,opt,name=new_pts,json=newPts,proto3" json:"new_pts,omitempty"`
	NewUnorderedPts int64                  `protobuf:"varint,2,opt,name=new_unordered_pts,json=newUnorderedPts,proto3" json:"new_unordered_pts,omitempty"`
	Chats           []*common.ChatState    `protobuf:"bytes,3,rep,name=chats,proto3" json:"chats,omitempty"`
	Profile         *common.ProfileState   `protobuf:"bytes,4,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetSnapshotResponse) Reset() {
	*x = GetSnapshotResponse{}
	mi := &file_sync_sync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapshotResponse) ProtoMessage() {}

func (x *GetSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_sync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapshotResponse.ProtoReflect.Descriptor instead.
func (*GetSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_sync_sync_proto_rawDescGZIP(), []int{5}
}

func (x *GetSnapshotResponse) GetNewPts() int64 {
	if x != nil {
		return x.NewPts
	}
	return 0
}

func (x *GetSnapshotResponse) GetNewUnorderedPts() int64 {
	if x != nil {
		return x.NewUnorderedPts
	}
	return 0
}

func (x *GetSnapshotResponse) GetChats() []*common.ChatState {
	if x != nil {
		return x.Chats
	}
	return nil
}

func (x *GetSnapshotResponse) GetProfile() *common.ProfileState {
	if x != nil {
		return x.Profile
	}
	return nil
}

var File_sync_sync_proto protoreflect.FileDescriptor

const file_sync_sync_proto_rawDesc = "" +
	"\n" +
	"\x0fsync/sync.proto\x12\x04sync\x1a\x12common/types.proto\"*\n" +
	"\x0fGetStateRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"I\n" +
	"\x10GetStateResponse\x12\x10\n" +
	"\x03pts\x18\x01 \x01(\x03R\x03pts\x12#\n" +
	"\runordered_pts\x18\x02 \x01(\x03R\funorderedPts\"f\n" +
	"\x14GetDifferenceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x10\n" +
	"\x03pts\x18\x02 \x01(\x03R\x03pts\x12#\n" +
	"\runordered_pts\x18\x03 \x01(\x03R\funorderedPts\"\x86\x01\n" +
	"\x15GetDifferenceResponse\x12\x17\n" +
	"\anew_pts\x18\x01 \x01(\x03R\x06newPts\x12*\n" +
	"\x11new_unordered_pts\x18\x02 \x01(\x03R\x0fnewUnorderedPts\x12(\n" +
	"\aupdates\x18\x03 \x03(\v2\x0e.common.UpdateR\aupdates\"S\n" +
	"\x12GetSnapshotRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12$\n" +
	"\x0elimit_per_chat\x18\x02 \x01(\x05R\flimitPerChat\"\xb3\x01\n" +
	"\x13GetSnapshotResponse\x12\x17\n" +
	"\anew_pts\x18\x01 \x01(\x03R\x06newPts\x12*\n" +
	"\x11new_unordered_pts\x18\x02 \x01(\x03R\x0fnewUnorderedPts\x12'\n" +
	"\x05chats\x18\x03 \x03(\v2\x11.common.ChatStateR\x05chats\x12.\n" +
	"\aprofile\x18\x04 \x01(\v2\x14.common.ProfileStateR\aprofile2H\n" +
	"\vSyncService\x129\n" +
	"\bGetState\x12\x15.sync.GetStateRequest\x1a\x16.sync.GetStateResponseB'Z%github.com/DarkXPixel/Vibe/proto/syncb\x06proto3"

var (
	file_sync_sync_proto_rawDescOnce sync.Once
	file_sync_sync_proto_rawDescData []byte
)

func file_sync_sync_proto_rawDescGZIP() []byte {
	file_sync_sync_proto_rawDescOnce.Do(func() {
		file_sync_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sync_sync_proto_rawDesc), len(file_sync_sync_proto_rawDesc)))
	})
	return file_sync_sync_proto_rawDescData
}

var file_sync_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_sync_sync_proto_goTypes = []any{
	(*GetStateRequest)(nil),       // 0: sync.GetStateRequest
	(*GetStateResponse)(nil),      // 1: sync.GetStateResponse
	(*GetDifferenceRequest)(nil),  // 2: sync.GetDifferenceRequest
	(*GetDifferenceResponse)(nil), // 3: sync.GetDifferenceResponse
	(*GetSnapshotRequest)(nil),    // 4: sync.GetSnapshotRequest
	(*GetSnapshotResponse)(nil),   // 5: sync.GetSnapshotResponse
	(*common.Update)(nil),         // 6: common.Update
	(*common.ChatState)(nil),      // 7: common.ChatState
	(*common.ProfileState)(nil),   // 8: common.ProfileState
}
var file_sync_sync_proto_depIdxs = []int32{
	6, // 0: sync.GetDifferenceResponse.updates:type_name -> common.Update
	7, // 1: sync.GetSnapshotResponse.chats:type_name -> common.ChatState
	8, // 2: sync.GetSnapshotResponse.profile:type_name -> common.ProfileState
	0, // 3: sync.SyncService.GetState:input_type -> sync.GetStateRequest
	1, // 4: sync.SyncService.GetState:output_type -> sync.GetStateResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_sync_sync_proto_init() }
func file_sync_sync_proto_init() {
	if File_sync_sync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sync_sync_proto_rawDesc), len(file_sync_sync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sync_sync_proto_goTypes,
		DependencyIndexes: file_sync_sync_proto_depIdxs,
		MessageInfos:      file_sync_sync_proto_msgTypes,
	}.Build()
	File_sync_sync_proto = out.File
	file_sync_sync_proto_goTypes = nil
	file_sync_sync_proto_depIdxs = nil
}
