postgresql:
  host: "postgres-auth"
  port: 5432
  user: "chat_user"
  password: "chat_pass"
  dbname: "vibe_chat"
  sslmode: "disable"
grpc:
  port: 50034
  timeout: 60s

auth-service:
  host: "auth-service"
  port: 50032