# Allow all connections without password (for dev)
#host all all 0.0.0.0/0 trust
local   all             all                                     trust
host    all             all             172.19.0.0/16           md5
