apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: vibe
build:
  artifacts:
  - image: vibe/auth-service
    context: ./services/auth-service
    docker:
      dockerfile: Dockerfile
      secrets:
        - id: buf_token
          env: BUF_TOKEN
  - image: vibe/user-service
    context: ./services/user-service
    docker:
      dockerfile: Dockerfile
      secrets:
        - id: buf_token
          env: BUF_TOKEN
  local:
    push: false
    useBuildkit: true
  tagPolicy:
    gitCommit: {}

deploy:
  helm:
    releases:
      - name: auth-service
        chartPath: helm/services/auth-service
        namespace: auth
        createNamespace: true
        setValueTemplates:
          #image: "{{ .IMAGE_FULLY_QUALIFIED_NAME }}"
          # image.tag: "sha256:{{.DIGEST_HEX}}"
       
      - name: user-service
        chartPath: helm/services/user-service
        namespace: user
        createNamespace: true
      - name: istio
        chartPath: istio/istiod
        namespace: istio-system
      # - name: envoy
      #   chartPath: helm/envoy
        
        # setValueTemplates:
        #   image.tag: "{{.DIGEST_HEX}}"
