apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: vibe
build:
  artifacts:
  - image: vibe/auth-service
    context: ./services/auth-service
    docker:
      dockerfile: Dockerfile
      secrets:
        - id: buf_token
          env: BUF_TOKEN
  # - image: vibe/user-service
  #   context: .
  #   docker:
  #     dockerfile: services/user-service/Dockerfile
  local:
    push: false
    useBuildkit: true
  tagPolicy:
    gitCommit: {}

deploy:
  helm:
    releases:
      - name: auth-service
        chartPath: helm/services/auth-service
        namespace: auth
        createNamespace: true
      # - name: user-service
      #   chartPath: helm/services/user-service
      #   namespace: user
      #   createNamespace: true
