database:
  host: "postgres-auth"
  port: 5432
  user: "auth_user"
  password: "auth_pass"
  dbname: "vibe_auth"
  sslmode: "disable"

user-service:
  host: "user-service"
  port: 50033
grpc:
  port: 50032
  timeout: 60s
redis:
  host: "redis"
  port: "6379"
  password: "password"
loki:
  host: "http://loki"
  port: 3100

JWT:
  secret: "008b057678d1f6cbc8ddced4b387b92334006894686164d1de8efe957c74ed88"

