apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql-cluster
  namespace: default
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  storage: 
    size: 4Gi
    storageClass: standard
  enableSuperuserAccess: true
  superuserSecret:
    name: postgres-superuser-secret
