apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-config
  namespace: default
data:
  POSTGRESQL_ADMIN_USER: "{{ .Values.config.postgres.adminUser }}"
  POSTGRESQL_HOST: "{{ .Values.config.database.host }}"
  POSTGRESQL_SSLMODE: "{{ .Values.config.database.sslmode }}"