apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-init-sql
  namespace: default
data:
  init-template.sql: |
    CREATE USER ${AUTH_USER} WITH PASSWORD '${AUTH_USER_PASSWORD}';
    -- CREATE USER $(USER_USER) WITH PASSWORD '$(USER_USER_PASSWORD)';
    -- CREATE USER $(CHAT_USER) WITH PASSWORD '$(CHAT_USER_PASSWORD)';
    -- CREATE USER $(SYNC_USER) WITH PASSWORD '$(SYNC_USER_PASSWORD)';
    CREATE USER ${POSTGRES_ADMIN_USER} WITH PASSWORD '${POSTGRES_ADMIN_PASSWORD}' SUPERUSER;

    CREATE DATABASE ${DB_AUTH} OWNER ${AUTH_USER};
    -- CREATE DATABASE $(DB_USER) OWNER $(USER_USER);
    -- CREATE DATABASE $(DB_CHAT) OWNER $(CHAT_USER);
    -- CREATE DATABASE $(DB_SYNC) OWNER $(SYNC_USER);

    GRANT ALL PRIVILEGES ON DATABASE ${DB_AUTH} TO ${AUTH_USER};
    -- GRANT ALL PRIVILEGES ON DATABASE $(DB_USER) TO $(USER_USER);
    -- GRANT ALL PRIVILEGES ON DATABASE $(DB_CHAT) TO $(CHAT_USER);
    -- GRANT ALL PRIVILEGES ON DATABASE $(DB_SYNC) TO $(SYNC_USER);

    REVOKE ALL ON DATABASE ${DB_AUTH} FROM PUBLIC;
    -- REVOKE ALL ON DATABASE $(DB_USER) FROM PUBLIC;
    -- REVOKE ALL ON DATABASE $(DB_CHAT) FROM PUBLIC;
    -- REVOKE ALL ON DATABASE $(DB_SYNC) FROM PUBLIC;