apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
spec:
  serviceName: "postgresql"
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
      - name: postgresql
        image: {{ .Values.postgres.image }}
        env:
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: postgresql-config
              key: POSTGRESQL_ADMIN_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-secrets
              key: DB_PASSWORD
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgresql-data
          mountPath: /var/lib/postgresql/data
        readinessProbe:
          exec:
            command: ["pg_isready", "-h", "localhost", "-p", "5432", "-U", "postgres"]
          initialDelaySecond: 5
          periodSeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: postgresql-data
        {{- if .Values.devSecretsEnabled }}
        emptyDir: {}
        {{- else }}
        persistentVolumeClaim:
          claimName: postgres-pvc
        {{- end }}
      - name: init-sql
        configMap:
          name: postgresql-init-sql

---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: default
spec:
  selector:
    app: postgresql
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
