global:
  domain: localhost
  appNamespace: app
  ingressNamespace: istio-system

authService:
  host: auth-service.app.svc.cluster.local
  port: 50032
  introspect:
    timeoutMs: 250

routes:
  publicGrpc:
    - /auth.AuthService/Login
    - /health.HealthService/Check
  secure:
    defaultUpstream:
      host: api-gateway.app.svc.cluster.local
      port: 50051

security:
  mtlsMode: PERMISSIVE