postgres:
  host: "postgres-auth"
  port: 5432
  user: "message_user"
  password: "message_pass"
  dbname: "vibe_message"
  sslmode: "disable"
grpc:
  port: 50035
  timeout: 60s

auth-service:
  host: "auth-service"
  port: 50032