{{- if and .Values.auth.enabled .Values.auth.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.passwordSecret | default (printf "%s-redis-secret" .Values.clusterName) }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  password: {{ .Values.auth.password }}
{{- end }}