apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: edge-gw
  namespace: {{ .Values.global.appNamespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http2
      protocol: HTTP2
    hosts:
    - {{ .Values.global.domain }}